# Generated by Django 5.2.3 on 2025-06-15 15:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PricingConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=False)),
                ('days_applicable', models.JSONField(help_text="List of days this pricing applies to. e.g., ['Mon', 'Tue']")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('base_price', models.FloatField()),
                ('base_distance_km', models.FloatField()),
                ('additional_price_per_km', models.FloatField()),
                ('free_wait_minutes', models.IntegerField(default=3)),
                ('wait_charge_per_3min', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='ConfigChangeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('change_description', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pricing.pricingconfig')),
            ],
        ),
        migrations.CreateModel(
            name='TimeMultiplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upper_limit_minutes', models.IntegerField()),
                ('multiplier', models.FloatField()),
                ('config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_multipliers', to='pricing.pricingconfig')),
            ],
            options={
                'ordering': ['upper_limit_minutes'],
            },
        ),
    ]
